### ISSUE TITLE
수정

### ISSUE THREAD

**Issue by smalower** [danny50167/discord-dot#6]
수정 ❗️:

- [x] 도트 제비뽑기 - 임베드
- [x] 도트 운세 - 코드 주석처리
- [x] 도트 돗줘 - 코드 
- [x] 도트 잔액확인 || 잔액 - 코드
- [x] 도트 주식판매 - 주식판매가 안됨
- [x] 도트 주가 <회사이름> - 임베드
- [x] 도트 커맨드 - '도트 가위 | 바위 | 보' 로 수정

**Comment by danny50167** [comment]
Done :)
